ads/urls.py
from django.urls import path, include
from . import views
from django.views.decorators.csrf import csrf_exempt

urlpatterns=[
	path('producer/',views.categorylist, name='category-list'),
	path('updatead/<int:pk>/',views.updatead,name='update-ad'),
	path('deletead/<int:pk>/',views.deletead, name='delete-ad'),
	path('ad_filter',views.filteredAd, name='filter-ad'),
	path('detailad/<int:pk>/',views.detailad,name='detailad'),
	path('apply/<int:pk>/',views.apply, name='apply'),
	path('applications/<int:pk>/',views.allapplications,name='ad-apply'),
	path('applicationdetail/<int:pk>/<int:pk_app>/<int:pk_u>/',views.viewapplicationdetail, name= 'app-detail'),
	path('applicationdetail/delete/',csrf_exempt(views.regect), name="regect-appl"),
	path('applicationdetail/accept/',csrf_exempt(views.accept), name="accept-appl"),
	path('applicationdetail/hold/',csrf_exempt(views.hold), name="hold-appl"),
	path('updateadmin/<int:id>/<int:pk>/', views.updateadadmin, name="upad"),
	path('deleteadmin/<int:id>/<int:pk>/', views.deleteadadmin, name="delad"),
	path('startapplication/<int:pk>/',views.startapplication, name="start"),
]

applications/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ApplicationForm,name='appli'),
   
    ]

movieaudi/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from ads import views as ad_view
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('home/',views.home,name='home'),
    path('custom-admin/',include('accounts.urls')),
    path('',views.landing,name='landing'),
    path('registerphoto/',views.photographereg,name='photoreg'),
    path('registertalent/',views.talentreg,name='talreg'),
    path('registerecruter/',views.recrutereg,name='recreg'),
    path('ajax/validate_username/',csrf_exempt(views.validate_username),name='validate_username'),
    
    path('ads/<int:pk>/<int:pk_alt>/',ad_view.try_pks,name='try-der'),
    path('test/',csrf_exempt(ad_view.testvalidate),name='test'),
    path('reset_password/', auth_views.PasswordResetView.as_view(),name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('ajax/load-cities',views.load_cities, name='ajax_load_cities'),
    path('ajax/load-districts/',views.load_districts,name='ajax_load_dictrict'),
    path('download/',views.downloadfile),
    path('ad/',include('ads.urls')),
    
    path('payment/',include('payment.urls')),
    path('application/',include('applications.urls')),
    path('add_questions/',include('criteria.urls')),
]



if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py

from django.urls import path, include
from . import views

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('<int:pk>/', views.index,name='make-appointment'),
    path('test/',csrf_exempt(views.test)),
    path('pay/',csrf_exempt(views.payappointment),name='pay'),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from applications.models import PhotographerApplication
# Create your models here.
class Province(models.Model):
	name=models.CharField(max_length=100)
	def __str__(self):
		return self.name;

class District(models.Model):
	name=models.CharField(max_length=100)
	province=models.ForeignKey(Province,on_delete=models.CASCADE)
	def __str__(self):
		return self.name;


class Sector(models.Model):
	name =models.CharField(max_length=100)
	district=models.ForeignKey(District, on_delete=models.CASCADE)

	def __str__(self):
		return self.name;



class User(AbstractUser):
	
	RECRUTER='RC'
	TALENT='TL'
	PHOTOGRAPHER='PH'
	UNKNOWN='UN'
	TYPE_IN_CHOICES=[
		(RECRUTER,'Recruter'),
		(TALENT,'Talent'),
		(PHOTOGRAPHER,'Photographer'),
		(UNKNOWN,'Unknown'),

	]
	gender_list = (
		('Female','Female'),
		('Male', 'Male'),
	)
	type_in_choices=models.CharField(
		max_length=2,
		choices=TYPE_IN_CHOICES,
		default=UNKNOWN,
		)
	province=models.ForeignKey(Province,on_delete=models.CASCADE,null=True)
	district=models.ForeignKey(District,on_delete=models.CASCADE,null=True)
	sector=models.ForeignKey(Sector,on_delete=models.CASCADE,null=True)
	gender = models.CharField(max_length=10,choices=gender_list,default="Male")



class Category(models.Model):
	name=models.CharField(max_length=100)
	img=models.ImageField(null=True,upload_to='cat',default='thumb_photos.png')
	
	def __str__(self):
		return self.name


class RecruterApp(models.Model):
	gender_list = (
		('Female','Female'),
		('Male', 'Male'),
	)
	first_name = models.CharField(max_length = 60)
	lasT_name = models.CharField(max_length = 70)
	company_name = models.CharField(max_length=100,null=True)
	company_address = models.CharField(max_length=100,null=True)
	tin_number = models.CharField(max_length = 20,null=True)
	email = models.CharField(max_length = 90)
	is_rejected = models.BooleanField(default = False)
	is_employed =  models.BooleanField(default = False)
	province=models.ForeignKey(Province,on_delete=models.CASCADE,null=True)
	district=models.ForeignKey(District,on_delete=models.CASCADE,null=True)
	sector=models.ForeignKey(Sector,on_delete=models.CASCADE,null=True)
	gender = models.CharField(max_length=10,choices=gender_list,default="Male")

	def __str__(self):
		return self.company_name


class Recruter(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	company_name=models.CharField(max_length=100,null=True)
	company_address=models.CharField(max_length=100,null=True)
	originated_country=models.CharField(max_length=100,null=True)
	rec_application = models.OneToOneField(RecruterApp, on_delete=models.CASCADE, null=True)
	

	def __str__(self):
		return self.user.username + 'Recruter'


class Talent(models.Model):
	
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	category=models.ManyToManyField(Category,null=True)
	profile_picture=models.ImageField(upload_to='profile_picture',default='thumb_photos.png')

	def __str__(self):
		return self.user.username + 'Talent'

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		SIZE = 300, 300
		if self.profile_picture:
			pic = Image.open(self.profile_picture.path)
			pic.thumbnail(SIZE, Image.LANCZOS)
			pic.save(self.profile_picture.path)

class Portfolio(models.Model):
	img = models.ImageField(null=True,upload_to='potfolio',default='thumb_photos.png')
	talent = models.ForeignKey(Talent, on_delete=models.CASCADE)

class Photographer(models.Model):
	talents=models.ManyToManyField(Talent,through='Appointment')
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	img=models.ImageField(null=True,upload_to='pho',default='thumb_photos.png')

	is_employed=models.BooleanField(default=False)
	application=models.OneToOneField(PhotographerApplication, on_delete=models.CASCADE, null=True)


	


class PhotoImage(models.Model):
	appl = models.ForeignKey(PhotographerApplication,on_delete=models.CASCADE, null=True)
	image=models.ImageField(upload_to='photographer_image')



class Appointment(models.Model):
	TIMESLOT_LIST = (
		('09:00 – 09:30', '09:00 – 09:30'),
		('10:00 – 10:30', '10:00 – 10:30'),
		('11:00 – 11:30', '11:00 – 11:30'),
		('12:00 – 12:30', '12:00 – 12:30'),
		('13:00 – 13:30', '13:00 – 13:30'),
		('14:00 – 14:30', '14:00 – 14:30'),
		('15:00 – 15:30', '15:00 – 15:30'),
		('16:00 – 16:30', '16:00 – 16:30'),
		('17:00 – 17:30', '17:00 – 17:30'),
	)
	SERVICES_LIST = (
		('Photoshooting','Photoshooting'),
		('videomaking', 'videomaking'),
	)
	A_STATUS = (
		('attended','attended'),
		('canceled', 'canceled'),
		('Not attended','Not attended'),
	)
	date = models.DateField(default=None, null=True)
	photographers=models.ForeignKey(Photographer,on_delete=models.CASCADE)
	talent=models.ForeignKey(Talent,on_delete=models.CASCADE)
	timeslot = models.CharField(choices=TIMESLOT_LIST,null=True, max_length=50)
	request_service = models.CharField(choices = SERVICES_LIST, default='videomaking',max_length= 255)
	status=models.BooleanField(default=False)
	att_status = models.CharField(choices=A_STATUS, max_length= 255, default= 'Not attended')

	class Meta:
		unique_together = ('photographers', 'date', 'timeslot')


class WorkFolder(models.Model):
	display_image = models.ImageField(upload_to='fold')
	name = models.CharField(max_length =360)
	photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE)


class Photographerwork(models.Model):
	photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='work')
	fold = models.ForeignKey(WorkFolder, on_delete=models.CASCADE, null=True)


class Feedback(models.Model):
	photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE)
	talent=models.ForeignKey(Talent,on_delete=models.CASCADE,null=True)
	appointment = models.OneToOneField(Appointment,on_delete=models.CASCADE)
	description = models.TextField(null=True)


class CompanyBase(models.Model):
	company_name = models.CharField(max_length = 250)
	tin_number = models.CharField(max_length = 20)
	address = models.CharField(max_length =  300)
	owner_name = models.CharField(max_length= 60)

	def __str__(self):
		return self.company_name








# Create your models here.

ads/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
from accounts.models import Recruter, Talent, User, Category
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date
from .validators import file_size


class Ad(models.Model):
	name=models.CharField(max_length=100)
	recruter=models.ForeignKey(Recruter,on_delete=models.CASCADE)
	category=models.ForeignKey(Category,on_delete=models.CASCADE)
	talents=models.ManyToManyField(Talent,through='Application')
	date=models.DateField(default=None)
	img=models.ImageField(null=True,upload_to='ads',default='thumb_photos.png')
	apply_date=models.DateField(default=timezone.now)
	start_application = models.BooleanField(default=False)

	def __str__(self):
		return self.name

	@property
	def is_past_due(self):
		return date.today() > self.date
	@property
	def is_not_the_time(self):
		return date.today() < self.apply_date

	@property
	def is_cannot_add(self):
		return date.today() < self.apply_date


class Application(models.Model):


	STATUS_CHOICES = [
		('Accepted','Accepted'),
		('Rejected','Rejected'),
		('Hold','Hold'),
		('Not Decided','Not Decided')
	]

	name=models.CharField(max_length=100)
	talent=models.ForeignKey(Talent, on_delete=models.CASCADE,null=True)
	ads=models.ForeignKey(Ad, on_delete=models.CASCADE)
	video=models.FileField(upload_to="videos/",null=True,validators=[file_size])
	application_status = models.CharField(max_length=40, choices= STATUS_CHOICES, default='Not Decided')
	thumbnail=models.ImageField(upload_to="thumbnails/",null=True, default='thumb_photos.png')
	recruter = models.ForeignKey(Recruter, models.CASCADE, null=True)
	
	
	class Meta:
		unique_together=[['talent','ads']]


class ApplPictures(models.Model):
	img=models.ImageField(null=True,upload_to='applpictures',default='thumb_photos.png')
	appli = models.ForeignKey(Application, on_delete=models.CASCADE)









applications/models.py
from django.db import models


# Create your models here.

class PhotographerApplication(models.Model):
    app_choices = [ 
    ("1","Month"),
    ("2","Year"),
    ]
    type_work = [
        ("FR","Freelance"),
        ("CP","Company"),
    ]


    first_name=models.CharField(max_length=40)
    last_name=models.CharField(max_length=40)
    email=models.EmailField(max_length = 254,unique=True)
    name_of_photography_school=models.CharField(max_length=500)
    experience=models.IntegerField()
    experience_in_month_or_year= models.CharField(max_length=1,choices=app_choices)
    Type_of_Work = models.CharField(max_length=2,choices=type_work)
    is_rejected=models.BooleanField(default=True)
    is_employed=models.BooleanField(default=False)
    

    def __str__(self):
        return self.first_name

applications/forms.py
from django import forms
from .models import PhotographerApplication

class AppForm(forms.ModelForm):
    class Meta:
        model= PhotographerApplication
        exclude=['is_rejected','is_employed']

applications/views.py
from django.shortcuts import render, redirect
from .models import PhotographerApplication
from .forms import AppForm
from django.urls import reverse
from django.core.mail import send_mail
from django.contrib import messages
# Create your views here.

def ApplicationForm(request):
    num=0
    if request.method =='POST':
        app_form=AppForm(request.POST)
        if app_form.is_valid():
            exp=app_form.cleaned_data['experience_in_month_or_year']
            type_work=app_form.cleaned_data['Type_of_Work']
            num_exp=app_form.cleaned_data['experience']
            if exp == '2':
                num +=2
            
            if exp == '1':
                if int(num_exp) > 6:
                    num +=1
                
            if type_work == 'CP':
                num +=2

            if type_work == 'FR':
                num +=1
            
            if num >= 3:

                app_form.instance.is_rejected=False
                app=app_form.save()
                
                send_mail(
                    'Link Application Continues',
                    f"http://127.0.0.1:8000/custom-admin/upld/{app.id}",
                    'kausarbhimani7@gmail.com',
                    [app.email],
                    fail_silently=False,
                )
                messages.success(request, 'Congratulations you have passed the Fiest Stage of selection ')
                return redirect(reverse ('upload-file', kwargs={"pk":app.id}))
            
            else:
                app_form.instance.is_rejected=True
                app_form.save()
                app_form=AppForm()

                context={
                    'app_form':app_form
                }
                
                        

    else:
        app_form=AppForm()
        context={
            'app_form':app_form
        }
        return render(request,'applicat.html',context)


payment/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .task import sleepy
from accounts.models import Photographer, Appointment
from django.http import JsonResponse, HttpResponse
# Create your views here.
from accounts.apointments import AppointmentForm
import datetime
from accounts.models import Appointment
from .models import Payment
import json
from django.contrib.auth.decorators import login_required

@login_required
def index(request,pk):
	ph= Photographer.objects.get(id=pk)


	form = AppointmentForm()
	return render(request, 'appointment_form.html', {'form': form,'ph':ph})


def test(request, *args,**kwargs):
	ph= request.POST.get('ph')
	date= request.POST.get('date')
	date =datetime.datetime.strptime(date,'%m/%d/%Y').strftime('%Y-%m-%d')
	ph = Photographer.objects.get(id=ph)
	appt= Appointment.objects.filter(photographers = ph, date=date ).first()
	app= Appointment.objects.filter(photographers = ph, date=date ).values('timeslot')
	print(app)
	if not appt:
		data ={
			'choices' : ""
		}
		return JsonResponse(data)
	
	data = {
		'choices': appt.timeslot
	}
	app=list(app)
	return JsonResponse(app, safe=False)

def validate_username(request):
    username = request.POST.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    print(username)
    return JsonResponse(data)


def payappointment(request):
	user= request.user
	talen = user.talent
	body = json.loads(request.body)
	date= body['date']
	date = datetime.datetime.strptime(date,'%m/%d/%Y').strftime('%Y-%m-%d')
	serv = body['sev']
	ph_id=body['ph']
	pho= Photographer.objects.get(id=ph_id)
	appointment = Appointment()
	appointment.date=date
	appointment.timeslot= body['timeslot']
	appointment.talent=talen
	appointment.photographers=pho
	appointment.request_service = serv
	appointment.save()
	payment = Payment()
	payment.txt_ref=body['txt']
	payment.talent=talen
	payment.photographer=pho
	payment.appointment=appointment
	payment.transaction_id=body['tr_id']
	payment.status = body['status']
	payment.save()

	print("body: " ,body)
	return JsonResponse("payment completed ", safe=False)



questions/views.py
from django.shortcuts import render

# Create your views here.

templates/appointment_form.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <link rel="stylesheet" type="text/css" href="/static/css/registertalent.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.min.css" integrity="sha256-/8xGgcV6Mp9fFa2u2lLYOWYNluCdrHEvBfiwhpkD/Js=" crossorigin="anonymous" />

   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/theme.min.css" integrity="sha256-j5WK5GB3+w3i2jRf0bV9dkjJ+mm+TiSEG6WgNiD+gWk=" crossorigin="anonymous" />

   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css" integrity="sha256-rxais37anKUnpL5QzSYte+JnIsmkGmLG+ZhKSkZkwVM=" crossorigin="anonymous" />
	{% load crispy_forms_tags %}
    
    
</head>
<body>
<div class="form-box">
<div class="form-container">
<div class="panel panel-default">
    <div class="panel-body">
        <section id="form-wrapper">
            <form  class="appointment-form">
               
                {{ form.as_p }}
               

             
            </form>
            <button class="btn btn-primary" onClick="makePayment()">Pay</button>
            
        </section>
    </div>
</div>
</div>
</div>




<script src="https://checkout.flutterwave.com/v3.js"></script>


<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="text/javascript" src="//code.jquery.com/jquery-1.11.3.min.js"></script>
 <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
  crossorigin="anonymous">
</script>

<!-- this file was missing -->
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>

<!-- this file was moved after the jQuery Datatables library was laoded -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>


<script type="text/javascript">


    $('#id_date').change(function(){
        var time =["09:00 – 09:30","10:00 – 10:30","11:00 – 11:30","12:00 – 12:30"]
        var dat= $(this).val();
        console.log(dat)
        $.ajax({
            url:'/payment/test/',
            method:'POST',
            data:{
                'date': dat,
                'ph' : {{ ph.id }}
            },
            success:function(data){
                    
                    console.log(data.length)
                    for (var j=0 ; j<data.length; j++){
                        console.log(data[j].timeslot)
                        t = time.indexOf(data[j].timeslot)
                    
                        if (t > -1) {
                        time.splice(t, 1);
                        }
                    }
                    
                    
                    
                    
                    
                    var newslots ={};
                    var i;
                    for(i=0;i<time.length; i++){
                        newslots[time[i]] = time[i]
                    }

                    var $el = $("#id_timeslot");
                    
                    $el.empty();
                    $.each(newslots, function(key,value) {
                    $el.append($("<option></option>")
                       .attr("value", value).text(key));

                   

});
            }
        })
    })

    $(document).ready(function(){
		var dateToday = new Date();
		$('#id_date').datepicker({
			changeYear:true,
			changeMonth:true,
			minDate: dateToday,
			dateformat:'yy-mm-dd',
		})
    })
</script>

<script>
  var ema = "{{ user.email }}";
  var time= new Date().getUTCMilliseconds();
  txt= time + Math.random()
  function postdata(data){
      var date= document.getElementById('id_date').value;
      var timeslot = document.getElementById('id_timeslot').value;
      var status = data.status
      var txt = data.tx_ref
      var transaction_id = data.transaction_id
      var url ="{% url 'pay' %}"
      var e = document.getElementById('id_request_service')
      var sev = e.value;


      fetch(url,{
          method: 'POST',
          body : JSON.stringify({
              'date': date,
              'timeslot': timeslot,
              'ph' : {{ ph.id }},
              'status' : status,
              'txt' : txt,
              'tr_id'  : transaction_id,
              'sev' : sev


          })
      }).then(response => {
          window.location.href="{% url 'talappoint'%}"
      }
          
      )
  }

  function makePayment() {
    FlutterwaveCheckout({
      public_key: "",
      tx_ref: txt,
      amount: 300,
      currency: "RWF",
      payment_options: " ",
      customer: {
        email: ema ,
        phone_number: " ",
        name: "Flutterwave Developers",
      },
      callback: function (data) { // specified callback function
        postdata(data)
      },
      customizations: {
        title: "Appointment",
        description: "Appointment with photographer",
        
      },
    });
  }

</script>

</body>
</html

templates/payment.html
<form>
  <script src="https://checkout.flutterwave.com/v3.js"></script>
  <button type="button" onClick="makePayment()">Pay Now</button>
</form>

<script>
  function makePayment() {
    FlutterwaveCheckout({
      public_key: "FLWPUBK_TEST-6f186c78fd1fdd566d14fa919c768f9d-X",
      tx_ref: "RX868",
      amount: 300,
      currency: "RWF",
      payment_options: "",
      customer: {
        email: "bhimanisaiyada7@gmail.com",
        phone_number: "",
        name: "Flutterwave Developers",
      },
      callback: function (data) { // specified callback function
        console.log(data);
      },
      customizations: {
        title: "My store",
        description: "Payment for items in cart",
        
      },
    });
  }
</script>

templates/questiondelete.html
{% extends "recruterbase.html" %}
{% block content %}
	<div class="content-section">
        <p> Are you sure you want to delete {{ question.name }}
		<form method="POST">
			{% csrf_token %}
			
            <a href ="{% url 'recruter-dash' %}"> cancel </a>
            <button type="submit" class="btn btn-danger">Delete</button>
		</form>
			
	</div>
{% endblock content %}

templates/testad.html
<!DOCTYPE html>

<html>
{% load crispy_forms_tags %}
<head>
	<title></title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
{{ a_form|crispy }}
<div class="form-group">
		<button class="btn btn-outline-info" type="submit">Register</button>
</div>
</form>




<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.min.css" integrity="sha256-/8xGgcV6Mp9fFa2u2lLYOWYNluCdrHEvBfiwhpkD/Js=" crossorigin="anonymous" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/theme.min.css" integrity="sha256-j5WK5GB3+w3i2jRf0bV9dkjJ+mm+TiSEG6WgNiD+gWk=" crossorigin="anonymous" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css" integrity="sha256-rxais37anKUnpL5QzSYte+JnIsmkGmLG+ZhKSkZkwVM=" crossorigin="anonymous" />


<script
  src="https://code.jquery.com/jquery-3.5.0.min.js"
  integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
  crossorigin="anonymous">
  </script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
  crossorigin="anonymous">
</script>
<script type="text/javascript">
	$(document).ready(function(){
		var dateToday = new Date();
		$('#id_date').datepicker({
			changeYear:true,
			changeMonth:true,
			minDate: dateToday,
			dateformat:'yy-mm-dd',
		})
		/*
		$('#id_date').change(function(){
			var dat= $(this).val();
			$.ajax({
				url:'/test/',
				method:'POST',
				data:{
					date: dat
				},
				success:function(data){
					if(data.is_appoint){
						alert("A user with this username already exists.");
						$('#id_date').val('')
					}
				}
			})
		})
		*/
	}

	)
</script>
</body>
</html>